# typed: false
# frozen_string_literal: true

# This file was generated by d-led/console-chess (scripts/generate-homebrew-formula.sh).
# Do not edit by hand; update via the release workflow or re-run the generator.
class Chess < Formula
  desc "TUI chess in Java"
  homepage "https://github.com/d-led/console-chess"
  version "0.0.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/chess-0.0.1-macos-arm64.tar.gz"
      sha256 "03509b7870a6c49e42e5a7014a2852b93134960736c85f36ffdeaf1e11e16620"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/chess-0.0.1-linux-arm64.tar.gz"
      sha256 "63763fc1a04487dc3d3dcec4ee301ba8976fa8a4c9f813ff0f3f69e47213b6fb"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/chess-0.0.1-linux-x64.tar.gz"
      sha256 "434e642aa58e23da6fe2cfb0e985dea857a8ab57664e2999b9df29c16cbdc64c"
    end
  end

  def install
    bin.install "chess"
  end

  test do
    assert_match "Usage: chess", shell_output("#{bin}/chess --help")
  end
end
