# typed: false
# frozen_string_literal: true

# Generated by d-led/commentray (scripts/generate-homebrew-formula.mjs). Do not edit by hand; update via CI or re-run the generator.
class Commentray < Formula
  desc "Commentray — paired commentary markdown CLI (standalone binary)"
  homepage "https://github.com/d-led/commentray"
  version "0.3.3"
  license "MPL-2.0"

  on_macos do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-arm64"
      sha256 "96306ca7413b5c3702eb6efb7f162662790db513b8bc4a647d798549693f7d79"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-x64"
      sha256 "258ce0458bae491ca24446042c0661abc298868130235cdec73f1c1b1910251f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-arm64"
      sha256 "d03157bb877075c576843ed35c0ea5843c47279e1d6a098cf3be7e5d47c0862e"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-x64"
      sha256 "98014b0c9a9e45291b899c0817ba1e0ef8d328683a143f61f627d679bf1de1bd"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "commentray-darwin-arm64" => "commentray"
      else
        bin.install "commentray-darwin-x64" => "commentray"
      end
    elsif OS.linux?
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-arm64" => "commentray"
      elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-x64" => "commentray"
      else
        odie "Unsupported Linux CPU architecture"
      end
    else
      odie "Unsupported platform"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commentray --version")
  end
end
