# typed: false
# frozen_string_literal: true

# Generated by d-led/commentray (scripts/generate-homebrew-formula.mjs). Do not edit by hand; update via CI or re-run the generator.
class Commentray < Formula
  desc "Commentray — paired commentary markdown CLI (standalone binary)"
  homepage "https://github.com/d-led/commentray"
  version "0.3.5"
  license "MPL-2.0"

  on_macos do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-arm64"
      sha256 "3c0b7e4e69240257e160402696f8f34270730a68e9f7b3cea91ebce2fc251ca9"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-x64"
      sha256 "2381b055f496ee748fc5417ad8956d6a0a8d038011949f58dbc1db69b04496e7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-arm64"
      sha256 "b9542b17d580eff35fc622d6850d6702999139886aa2243a55ab38d7866de13b"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-x64"
      sha256 "676db99750980bc50876129688e8eb9cbdacffbb55badfd6ae0e166ca0ecbf3f"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "commentray-darwin-arm64" => "commentray"
      else
        bin.install "commentray-darwin-x64" => "commentray"
      end
    elsif OS.linux?
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-arm64" => "commentray"
      elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-x64" => "commentray"
      else
        odie "Unsupported Linux CPU architecture"
      end
    else
      odie "Unsupported platform"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commentray --version")
  end
end
