# typed: false
# frozen_string_literal: true

# Generated by d-led/commentray (scripts/generate-homebrew-formula.mjs). Do not edit by hand; update via CI or re-run the generator.
class Commentray < Formula
  desc "Commentray — paired commentary markdown CLI (standalone binary)"
  homepage "https://github.com/d-led/commentray"
  version "0.3.2"
  license "MPL-2.0"

  on_macos do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-arm64"
      sha256 "608cbe09542de460c56eaaccb355b561e326aece01f3b1e17b5a8c80ea40726d"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-darwin-x64"
      sha256 "8aec5bf67f593213d69570d253665c32eb1d459a2bc9db0cd0211b7219b8f04b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-arm64"
      sha256 "0549cdbdda83b08ffc99655eb0e1b4f7d35f30aaea9754c151ffbe126f71b82c"
    end
    on_intel do
      url "https://github.com/d-led/commentray/releases/download/v#{version}/commentray-linux-x64"
      sha256 "7d99e9cb1f63d6c87993cdea1414d67d8ca042bd98efa201dc7f6c85acca7e20"
    end
  end

  def install
    if OS.mac?
      if Hardware::CPU.arm?
        bin.install "commentray-darwin-arm64" => "commentray"
      else
        bin.install "commentray-darwin-x64" => "commentray"
      end
    elsif OS.linux?
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-arm64" => "commentray"
      elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
        bin.install "commentray-linux-x64" => "commentray"
      else
        odie "Unsupported Linux CPU architecture"
      end
    else
      odie "Unsupported platform"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/commentray --version")
  end
end
