# typed: false
# frozen_string_literal: true

# This file was generated by d-led/console-chess (scripts/generate-homebrew-formula.sh).
# Do not edit by hand; update via the release workflow or re-run the generator.
class ConsoleChess < Formula
  desc "TUI chess in Java"
  homepage "https://github.com/d-led/console-chess"
  version "0.0.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-arm64.tar.gz"
      sha256 "6dba548a49e53c2491dfecb1bb24881bfa8bf3f66d03e20c58df1906233aae8d"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-x64.tar.gz"
      sha256 "6ec174d1ac9b2e2d3e5f5ad03ed3d15b375e660986f64fd4f10b83e6ad8472a1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-arm64.tar.gz"
      sha256 "da2f1acb159bad58548c242e123959c1fd40686a089fe10fb87b6b477480b773"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-x64.tar.gz"
      sha256 "11887780eb2021f63e70ef6389d4e03e3c9e1be8d3dc5ae87d9e0a698b8c0525"
    end
  end

  def install
    bin.install "console-chess"
  end

  test do
    assert_match "Usage: console-chess", shell_output("#{bin}/console-chess --help")
  end
end
