# typed: false
# frozen_string_literal: true

# This file was generated by d-led/console-chess (scripts/generate-homebrew-formula.sh).
# Do not edit by hand; update via the release workflow or re-run the generator.
class ConsoleChess < Formula
  desc "TUI chess in Java"
  homepage "https://github.com/d-led/console-chess"
  version "0.0.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-arm64.tar.gz"
      sha256 "f46859fbd8be6c7aa926197470fad72b12e3c2db915dac475367f6f1a3a086da"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-x64.tar.gz"
      sha256 "fcab980b7715f3892d7d5464b90385c3aebe0358052c6bd55cd2873301dc7803"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-arm64.tar.gz"
      sha256 "d25264d2735906b33cbcf599b416550d44c7c1d98035b6b4ddeb1e103f1f4e48"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-x64.tar.gz"
      sha256 "088553ace69a018012a1f9744f2e471fa8be44ba6d785ccb255392fc294e2ded"
    end
  end

  def install
    bin.install "console-chess"
  end

  test do
    assert_match "Usage: console-chess", shell_output("#{bin}/console-chess --help")
  end
end
