# typed: false
# frozen_string_literal: true

# This file was generated by d-led/console-chess (scripts/generate-homebrew-formula.sh).
# Do not edit by hand; update via the release workflow or re-run the generator.
class ConsoleChess < Formula
  desc "TUI chess in Java"
  homepage "https://github.com/d-led/console-chess"
  version "0.0.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-arm64.tar.gz"
      sha256 "f2dff59bc68b1f471aab7d778d8d685724785d4bf1da4c03615edf003d034f2c"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-macos-x64.tar.gz"
      sha256 "b58ed16fdc02eb6383abf9af6d3b7e7e034e2cb7e074b0b17be98e45b824f7ba"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-arm64.tar.gz"
      sha256 "b5e2cb013a38f8f6245a8c1f8703dedd90ee2d5b6a324cec56268d7b6b44400b"
    else
      url "https://github.com/d-led/console-chess/releases/download/v0.0.1/console-chess-0.0.1-linux-x64.tar.gz"
      sha256 "70d1f7abe57dabf505360e91ac176f80c47988c4bee6ebfc8b0741806699ca7e"
    end
  end

  def install
    bin.install "console-chess"
  end

  test do
    assert_match "Usage: console-chess", shell_output("#{bin}/console-chess --help")
  end
end
