# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pathdebug < Formula
  desc ""
  homepage "https://github.com/d-led/pathdebug"
  version "0.1.3"

  on_macos do
    url "https://github.com/d-led/pathdebug/releases/download/v0.1.3/pathdebug_Darwin_all.tar.gz"
    sha256 "523f6cafe867cd9f7fa20272d19106de0331fdd4b734ec5a43257d048bc1de1e"

    def install
      bin.install "pathdebug"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/d-led/pathdebug/releases/download/v0.1.3/pathdebug_Linux_x86_64.tar.gz"
      sha256 "77324269aa3913e9ec938af9dc87994ff67a25b64bc8cbdda2320109bf1f096f"

      def install
        bin.install "pathdebug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d-led/pathdebug/releases/download/v0.1.3/pathdebug_Linux_arm64.tar.gz"
      sha256 "b7ab7dd8a8643fcaf6f3d49ddce6122b2b6b34af0b4b84fb3875a7ad8060e322"

      def install
        bin.install "pathdebug"
      end
    end
  end
end
