# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pathdebug < Formula
  desc ""
  homepage "https://github.com/d-led/pathdebug"
  version "0.3.11"

  on_macos do
    url "https://github.com/d-led/pathdebug/releases/download/v0.3.11/pathdebug_Darwin_all.tar.gz"
    sha256 "aa9e473d4f82e156eddc87a1a9b9643da385eb291e2529924a6fadd5e945824a"

    def install
      bin.install "pathdebug"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/d-led/pathdebug/releases/download/v0.3.11/pathdebug_Linux_x86_64.tar.gz"
        sha256 "64b14ea362dc51baed4150957679b6dfc23230bb2c06c72e35f6ecd4eed03a09"

        def install
          bin.install "pathdebug"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/d-led/pathdebug/releases/download/v0.3.11/pathdebug_Linux_arm64.tar.gz"
        sha256 "bb4d38d868bacadb2b02c1055f7d5cd49433326683294f00bd9e1594bd319e87"

        def install
          bin.install "pathdebug"
        end
      end
    end
  end
end
