# This file was generated by GoReleaser. DO NOT EDIT.
cask "mermaid2tgf" do
  name "mermaid2tgf"
  desc ""
  homepage "https://github.com/d-led/mermaid2tgf"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mermaid2tgf"

  on_macos do
    url "https://github.com/d-led/mermaid2tgf/releases/download/v#{version}/mermaid2tgf_Darwin_all.tar.gz",
        verified: "github.com/d-led/mermaid2tgf"
    sha256 "c3fb12436ff3eb16da4a6b2cd4b2ea35e48a4e1a938d304521678c79112a0281"
  end

  on_linux do
    on_intel do
      url "https://github.com/d-led/mermaid2tgf/releases/download/v#{version}/mermaid2tgf_Linux_x86_64.tar.gz",
        verified: "github.com/d-led/mermaid2tgf"
      sha256 "574aea36fed3638f19b7e76d7068da07d80d770a7ebc22b0f197d37be4a4235f"
    end
    on_arm do
      url "https://github.com/d-led/mermaid2tgf/releases/download/v#{version}/mermaid2tgf_Linux_arm64.tar.gz",
        verified: "github.com/d-led/mermaid2tgf"
      sha256 "3fef566691462b07852f7333db4c024cb22a37d9efe93cd1be86a2f814ddd081"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mermaid2tgf"]
    end
  end

  # No zap stanza required
end
